"""Pure pieces: log discovery and items, statement matching, attribution, features, seeds helpers."""
from datetime import datetime, timezone

from src.config import Config
from src.detect.python_ast import find_logs
from src.features.identify import identify_statement
from src.repo.history import Commit
from src.seeds.aidev import commit_attribution
from src.seeds.exclude import excluded_content, excluded_path
from src.seeds.prefilter import patch_lines
from src.track.attribution import PrIndex, attribute, pr_number_in
from src.track.match import change_record, hungarian, hunks_from_texts, match_file

HEAD = "import logging\nlog = logging.getLogger(__name__)\n\n"


def logs(src):
    return list(find_logs("a.py", src).statements)


def test_items_and_template():
    (a, b, c, d) = logs(HEAD + "def f(req, token, user):\n"
                               "    if req.debug:\n"
                               "        log.info(f'ok {user.id} {req.email} {token[:6]}')\n"
                               "    log.warning('x %s %s', mask(req.email), user, extra={'uid': user.id}, exc_info=True)\n"
                               "    log.info('a {} {k}'.format(x, k=y))\n"
                               "    print('hi', resp.json())\n")
    assert a.template == "ok {} {} {}" and a.conditions == ("req.debug",)
    assert [(i.expr, i.core, i.wrappers) for i in a.items] == [
        ("user.id", "user.id", ()), ("req.email", "req.email", ()), ("token[:6]", "token", ("slice",))]
    assert [(i.core, i.wrappers, i.key, i.role) for i in b.items] == [
        ("req.email", ("mask",), None, "value"), ("user", (), None, "value"), ("user.id", (), "uid", "value"),
        ("<exc_info>", (), None, "exception")]
    assert [(i.expr, i.key) for i in c.items] == [("x", None), ("y", "k")]
    assert d.sink == "print" and [i.expr for i in d.items] == ["resp.json()"]
    assert logs(HEAD + "print('x')\n") and not find_logs("a.py", HEAD + "print('x')\n", False).statements


def test_match_duplicates_by_position_and_modified():
    a = HEAD + "def f(user):\n    print('done')\n    log.info('login %s', user.email)\n    print('done')\n"
    b = HEAD + "def f(user):\n    x = 1\n    print('done')\n    log.info('login %s', user.id)\n    print('done')\n"
    r = match_file(logs(a), logs(b), hunks_from_texts(a, b))
    kinds = sorted((p.kind, p.before.line, p.after.line) for p in r.pairs)
    assert kinds == [("modified", 6, 7), ("unchanged", 5, 6), ("unchanged", 7, 8)]
    assert not r.added and not r.deleted
    rec = change_record(*[(p.before, p.after) for p in r.pairs if p.kind == "modified"][0])
    assert rec["items_added"] == ["user.id"] and rec["items_removed"] == ["user.email"] and not rec["message_changed"]


def test_match_deleted_added_and_many_to_many():
    a = HEAD + "def f():\n    log.info('one %s', a)\n    log.info('two %s', b)\n"
    b = HEAD + "def f():\n    log.info('two %s', b2)\n    log.info('one %s', a2)\n    log.error('three')\n"
    r = match_file(logs(a), logs(b), hunks_from_texts(a, b))
    pairs = {p.before.template: p.after.template for p in r.pairs}
    assert pairs == {"one %s": "one %s", "two %s": "two %s"}
    assert [s.template for s in r.added] == ["three"]


def test_hungarian_is_optimal_not_greedy():
    # greedy would take (0,0)=0.9 then (1,1)=0.1; optimal is (0,1)+(1,0)=1.6
    assert sorted(hungarian([[0.9, 0.8], [0.8, 0.1]])) == [(0, 1), (1, 0)]


def test_patch_lines_and_exclusion():
    added, removed, trunc = patch_lines("@@ -1,2 +1,2 @@\n a\n-log.info(x)\n+log.info(y)")
    assert added == ["log.info(y)"] and removed == ["log.info(x)"] and not trunc
    cfg = Config()
    assert excluded_path("pkg/.venv/lib/site-packages/requests/api.py", cfg).startswith("dir:")
    assert excluded_path("proto/x_pb2.py", cfg) == "suffix:_pb2.py"
    assert excluded_path("app/main.py", cfg) is None
    assert excluded_content("# Generated by protoc. DO NOT EDIT\n", cfg)


def test_commit_attribution_rules():
    bots = Config().bots()
    assert commit_attribution("Copilot", "Copilot", "Copilot", bots) == "agent_commit"
    assert commit_attribution("maintainer", "Copilot", "Copilot", bots) == "non_agent_commit"
    assert commit_attribution("alice", "OpenAI_Codex", "alice", bots) == "agent_pr_unverified"
    assert commit_attribution("claude[bot]", "Copilot", "Copilot", bots) == "non_agent_commit"


def test_author_three_values_never_human_by_default():
    idx = PrIndex.build([{"number": 7, "agent": "Copilot", "commit_shas": ["a" * 40]}])
    at = datetime(2026, 1, 1, tzinfo=timezone.utc)
    c = lambda sha, msg, name="bob", email="b@x": Commit(sha, (), at, name, email, msg)
    assert attribute(c("a" * 40, "wip"), idx)["evidence"] == "aidev_pr_commit"
    assert attribute(c("b" * 40, "Add x (#7)"), idx)["author_kind"] == "agent"
    assert attribute(c("b" * 40, "Merge pull request #8 from a/b"), idx)["author_kind"] == "not_agent"
    assert attribute(c("b" * 40, "fix\n\nGenerated with [Claude Code]"), idx)["agent"] == "Claude_Code"
    assert attribute(c("b" * 40, "direct push"), idx)["author_kind"] == "unknown"
    assert pr_number_in("Title (#12)\n\nbody (#3)") == 12


def test_features_with_evidence():
    src = ("import logging, os\nfrom pydantic import BaseModel, EmailStr\nlog = logging.getLogger(__name__)\n"
           "class Req(BaseModel):\n    email: EmailStr\n"
           "class S:\n    def __init__(self):\n        self.api_key = os.getenv('OPENAI_API_KEY')\n"
           "    def run(self):\n        log.info('k %s', self.api_key)\n"
           "def f(req: Req, request):\n    token = make_token()\n"
           "    log.info(f'{req.email} {token[:4]} {len(items)}')\n"
           "    log.info('auth %s', request.headers['Authorization'])\n"
           "    log.info('password=hunter2')\n")
    st = {s.line: s for s in find_logs("a.py", src).statements}
    k = identify_statement(st[10], src)[0]
    assert "AUTH.api_key" in k["categories"] and "CFG.environment" in k["categories"]
    email, token, count = identify_statement(st[13], src)
    assert email["categories"] == ["PII.email"] and {e["kind"] for e in email["evidence"]} == {"name", "type"}
    assert token["categories"] == ["AUTH.access_token"] and token["wrappers"] == ["slice"]
    assert count["categories"] == []                              # unclassified, not "safe"
    assert identify_statement(st[14], src)[0]["categories"] == ["AUTH.authorization_header"]
    assert identify_statement(st[15], src)[-1]["role"] == "message"


def test_move_requires_same_message():
    a = HEAD + "def f(fn):\n    log.debug(f'Cache hit for {fn}')\n\n\ndef g():\n    pass\n"
    b = HEAD + "def f(fn):\n    pass\n\n\ndef g(fn):\n    x = 1\n    log.debug(f'Cache miss for {fn}')\n"
    r = match_file(logs(a), logs(b), hunks_from_texts(a, b))
    assert not any(p.kind == "moved" for p in r.pairs)
    c = HEAD + "def f(fn):\n    pass\n\n\ndef g(fn):\n    x = 1\n    log.debug(f'Cache hit for {fn}')\n"
    r = match_file(logs(a), logs(c), hunks_from_texts(a, c))
    assert [p.kind for p in r.pairs] in (["moved"], ["modified"], ["unchanged"])


def test_expression_names_matched_one_by_one():
    src = HEAD + "def f(payload_size, e2):\n    log.info('%d %s %s', ceil(payload_size / 1024), '=' * 70, e2)\n"
    rows = identify_statement(find_logs("a.py", src).statements[0], src)
    assert rows[0]["categories"] == []                             # payload_size is an aggregate
    from src.features.identify import has_data
    assert not has_data("'=' * 70") and has_data("user.email")


def test_commit_message_with_separator_bytes(tmp_path):
    import subprocess
    from src.repo.history import all_commits, first_parent_log
    r = tmp_path / "r"
    r.mkdir()
    run = lambda *a: subprocess.run(["git", "-C", str(r), *a], check=True, capture_output=True,
                                    env={"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@x", "GIT_COMMITTER_NAME": "t",
                                         "GIT_COMMITTER_EMAIL": "t@x", "PATH": "/usr/bin:/bin"})
    run("init", "-q", "-b", "main")
    (r / "a.py").write_text("x = 1\n")
    run("add", "a.py")
    run("commit", "-q", "-m", "weird \x1e record \x1f unit separator")
    (r / "a.py").write_text("x = 2\n")
    run("commit", "-qam", "second (#3)")
    cs = list(all_commits(r, "HEAD"))
    assert len(cs) == 2 and "record" in cs[1].message
    fp = [c for c, _ in first_parent_log(r, "HEAD", with_changes=True)]
    assert [c.message.split("\n")[0] for c in fp][1] == "second (#3)"


def test_path_kind():
    from src.report.dataset import path_kind
    assert path_kind("tests/unit/test_api.py") == "test"
    assert path_kind("pkg/foo_test.py") == "test"
    assert path_kind("examples/rag/demo.py") == "example"
    assert path_kind("docs/conf.py") == "docs"
    assert path_kind("scripts/migrate.py") == "script"
    assert path_kind("src/app/server.py") == "source"


def test_backward_snippet_keeps_only_the_tracked_log():
    from src.track.tracker import _snippet_statement
    like = logs(HEAD + "def f(user):\n    log.debug(f'switching to LDAP connection for user {user}')\n")[0]
    hunk = ["        user = rel['end_node']['name']", "        log.info(f'password changed to {pwd} for {user}')",
            "        log.debug(f'[+] switching to LDAP connection for user {user}')"]
    st = _snippet_statement("a.py", hunk, like, 0.5)
    assert st is not None and "switching" in st.code
    assert _snippet_statement("a.py", ["    x = {1: self._dcSync,", "         2: self._other}"], like, 0.5) is None


def test_taxonomy_logtrace2_address_and_ids():
    from src.features.taxonomy import match_identifier
    subs = lambda x: {f"{r[0]}.{r[1]}" for r in match_identifier(x)}
    for name in ("self.address", "ip_address", "mac_address", "home_address", "remote_node.address"):
        assert subs(name) == {"QID.address"}, name
    assert subs("conversation_id") == subs("message_id") == subs("chat_id") == {"QID.conversation_identifier"}
    assert subs("messages") == {"LLM.messages"} and subs("user_id") == {"QID.user_identifier"}
    assert "BIZ.request_body" not in subs("request_id")


def test_get_with_constant_key_uses_the_key():
    src = HEAD + "def f(__user__, result):\n    log.info('%s %s', __user__.get('email', 'anon'), result.get('count'))\n"
    rows = identify_statement(find_logs("a.py", src).statements[0], src)
    assert "PII.email" in rows[0]["categories"] and "access" in {e["kind"] for e in rows[0]["evidence"]}
