"""Assistant-authored decisions after source/context review; not keyword classification.
Every accepted scope is rechecked against each event's actual path/line diff.
Unmatched scopes require a conservative event-specific uncertainty record.
"""
RULES = [
 (21,'b6aa615df0b73508c304ef4f','Refresh installer banner (wider frame, resource links, tagline).','inferred',['format_consistency'],'推测横幅输出随已说明的 CLI 横幅刷新调整布局和文案。','banner'),
 (81,'cb3d74298fca5ec26fa970f4','Refactor python scripts into bun CLI app','inferred',['requirements_change'],'推测该输出随 Python 脚本整体迁移到 Bun CLI 而从原文件移除；未据此认定减少日志噪声。','deleted_file'),
 (82,'0dd6c6febbccffa7a9c107b2','The vibx CLI application currently uses scattered `console.log`/`console.error` calls for output. This makes it difficult to debug, analyze, and trace operations.','explicit',['diagnostics','format_consistency'],'将操作性控制台输出改为结构化 logger，便于调试、分析和追踪；不把仍保留的用户可见输出认作被删除。','vibereq_logger'),
 (111,'a2ab9b55218024a039137f29','Skip transcript redaction when checkpoints v2 is disabled','inferred',['requirements_change'],'推测该警告随转录处理一起受 v2 开关控制，从而不在仅启用 v1 时执行；并非从代码效果直接认定性能动机。','v2_guard'),
 (139,'3417e2ad70359054967c9074','ensuring cancellation signals and context values propagate correctly','explicit',['other'],'保留调用方上下文，使取消信号和上下文值沿调用链传递。','context_arg'),
 (141,'73b7eed0784fbba241edc4c4','Remove long-deprecated commands and aliases','inferred',['requirements_change'],'推测日志随已废弃 rewind 命令所在文件整体移除；不单独归因为日志降噪。','deleted_file'),
 (144,'9fd95422bb747332754bb3ca','Remove the auto-commit strategy entirely, making manual-commit the only strategy','inferred',['requirements_change'],'推测日志随自动提交策略代码整体退役而移除。','deleted_auto_commit'),
 (165,'8cf8c1cb2a059ff69697f947','Consider rewording the log message to reflect that no readable/local metadata was found (without implying a failure).','explicit',['message_accuracy'],'避免把正常的本地元数据缺失描述成解析器失败。','review_reword'),
 (183,'4de2e4b5e6613ec8fa11d121','Updated `macosNotifier` and `beeepNotifier` to use `context.WithoutCancel(ctx)` instead of `context.Background()` for fire-and-forget delivery.','explicit',['other'],'修复忽略现有请求上下文的 G118 问题，失败日志使用从调用方派生的通知上下文。','notifier_context'),
 (188,'8933df3db08b2b13748f2cdd','취소로 판정해 조용히 끝낸다','explicit',['noise_control','message_accuracy'],'将离开页面后的加载异常视为取消并安静结束，避免输出误导性的 Failed to load 错误。','screen_cancel'),
 (193,'55504edd15d0634f15fb6571','Delete the unused `apps/platform` Next.js host and `api/platform` service package.','inferred',['requirements_change'],'推测该日志随不再使用的平台服务文件整体移除。','deleted_file'),
 (194,'fa029f787caee67c030f100c','Remove `[function-tag]` prefixes from log messages — `inngestFunctionId` in ALS makes them redundant','explicit',['noise_control','format_consistency'],'移除与 ALS 自动上下文重复的函数标签前缀。','als_prefix'),
 (194,'fa029f787caee67c030f100c','Strip ALS-provided fields (`correlationId`, `provider`, `clerkOrgId`, `installationId`) from remaining log calls — these are auto-enriched via AsyncLocalStorage','explicit',['noise_control','format_consistency'],'移除由 AsyncLocalStorage 自动补充的重复字段。','als_field'),
 (194,'fa029f787caee67c030f100c','Remove redundant bookend logs (started/complete/done) from all 12 Inngest functions','inferred',['noise_control'],'推测删除发送完成消息是生命周期日志去重的一部分；PR 未逐条点名该消息。','als_complete'),
 (199,'ae7416e1b2104dd225aa08e6','Strip the entire neural-pipeline / event-stream stack from the monorepo','inferred',['requirements_change'],'推测日志随原 backfill 业务模块整体拆除而移除。','deleted_file'),
 (200,'04379012827bee16e2f851ad','Remove the activity recording helper, Inngest workflow, and `app/activity.record` event schema that wrote to that table.','inferred',['requirements_change'],'推测日志随活动记录功能及其文件整体删除而移除。','deleted_file'),
 (205,'6e650fd8667542a0e58b48be','retire the private hosted Lightfast product surfaces','inferred',['requirements_change'],'推测该输出随已退役产品的可观测性文件整体清理而移除。','deleted_file'),
 (207,'f51f3fe0d1bedd0cd6205b0b','every provider/connections/webhook/AI surface is deleted','inferred',['requirements_change'],'推测日志随 provider、连接、webhook 或 AI 模块整体拆除而移除。','deleted_file'),
 (215,'75f7456ef671a5ddd5e4974e','Complete project rebrand from Brain/brain/BRAIN to\nOsabio/osabio/OSABIO','explicit',['message_accuracy','requirements_change'],'项目改名时同步更新 CLI 提示中的名称、环境变量或配置路径。','rebrand'),
 (217,'3c32d832bce6202d4d22ecb5','Directory-to-entity mapping was unused. Remove the command\nimplementations, switch cases, and help text.','explicit',['message_accuracy','requirements_change'],'删除未使用的 map/unmap 命令时同步删除帮助文字。','map_help'),
 (233,'afdc02856c73506f8500202e','split `processing/tokenize` into datakit-style stage A + stage B with a shared core','inferred',['requirements_change'],'推测旧 tokenize 输出随阶段拆分而移除或重组，材料未单独提出降噪目的。','tokenize_removed'),
 (249,'cb28e3f676372579a3a4a666','chore: refactor package to remove logger injection','inferred',['other'],'推测改用默认 slog 是移除 logger 注入的整体重构的一部分；具体日志没有独立目的说明。','default_logger'),
 (254,'ba188140989e38ca43645722','chore: minor bug fix with respect to logging','inferred',['other'],'代码把 slog.Default() 调用简化为 slog 包函数，推测是统一默认日志调用方式；提交未交代具体缺陷原因。','slog_package'),
 (271,'06d66c593ccf7ade216ee4aa','single contributor-facing doc covering coverage-threshold','inferred',['message_accuracy'],'推测更新提示路径是为引导贡献者使用新的统一 ratchet 工作流文档。','ratchet_path'),
 (275,'62340e3391702ce36fd1a23b','Complete project rebrand from Brain/brain/BRAIN to Osabio/osabio/OSABIO','explicit',['message_accuracy','requirements_change'],'项目改名时同步更新 CLI 提示中的名称、环境变量或配置路径。','rebrand'),
 (278,'c1ab7ae057dc2c87baeecbcd','Directory-to-entity mapping was unused. Remove the command\nimplementations, switch cases, and help text.','explicit',['message_accuracy','requirements_change'],'删除未使用的 map/unmap 命令时同步删除帮助文字。','map_help'),
 (286,'912123b120bef91957f238d1','move debug writing functions to a separate module for better organization','inferred',['other'],'推测 debug 文件写入调用的名称调整服务于独立模块抽取，以改善代码组织。','write_step'),
 (307,'9c55d5f8568f9b3b8440b1e9','Treat existing position as skip (success=True) instead of error','inferred',['log_level','message_accuracy'],'推测 warning 改为 info 并使用 skip 图标，是为了与已有仓位属于正常跳过的语义一致。','trade_skip'),
 (317,'c596b9cf1c9151f1bfc41428','Switch to fullStream\nwhich exposes error parts with the actual upstream error message.','explicit',['diagnostics'],'记录真实上游流错误，避免只有笼统的无输出错误消息。','stream_errors'),
 (329,'8710d880fd8f80a813306cf6','normalized log levels in watch/client.py','explicit',['log_level'],'规范 watch/client.py 的日志级别；材料没有明确说明降噪或性能目的。','warning_debug'),
 (330,'2f6c7c5dfb37f32b8b8ea11e','Extract plant loop from __main__.py (526 -> 92\nlines) into reck/loop.py.','inferred',['other'],'推测原日志随 plant loop 抽取到独立模块而迁移，文本本身保留。','loop_move'),
 (338,'38ad5d9fbf4ca86a740253b3','replace logger.debug with logger.warning and structured extra payloads','explicit',['log_level','diagnostics'],'提高失败路径的日志可见性并增加结构化字段，满足明确提出的不再静默失败要求。','debug_warning'),
]

GROUP_NOTES = {
 3:'提交涉及 save.py 的异常日志；当前事件在 embeddings 文件，不能跨文件套用 Q-3 目的。',
 7:'Query logging 是 Ent 查询调试背景，不能直接解释目标 API 错误日志。',
 9:'日志器迁移说明点名 admin_handlers.go；invite_handlers.go 的目标语句需独立对应。',
 12:'ORM 迁移可解释业务上下文，但没有为未变的错误输出确立独立日志目的。',
 33:'final optimizations 和全仓审查请求过宽，无法可靠指定每条输出的修改目的。',
 37:'Bifrost 的非 2xx 代理错误日志说明并非 sidecar API reachability 成功消息的目的。',
 40:'PR 说明网络连通性，提交本身说明移除 subprocess；不能把二者混成日志目的。',
 54:'PR 的 session log 数据库事务讨论并非 Linear/调度器控制台输出的修改目的。',
 55:'版本发布标题未说明这些输出为何改变；精确提交到 PR 的补查遭遇认证过期。',
 82:'prompt 要求结构化操作日志，同时明确保留用户可见 console 输出；逐目标区分替换与重排。',
 85:'PR 明确谈 stderr→结构化日志，但目标已经使用 logging.Info；不得直接套用 stderr 目的。',
 117:'headHasReviewCheckpoint 的 Debug 说明不是 committed.go 目标去重警告的目的。',
 120:'目标现有 Debug 主要换 logCtx；PR 新增诊断的目的不能自动覆盖这一参数替换。',
 139:'只有确认上下文实参变化的目标使用明确目的；依赖/周边变化和变量重命名分别保守处理。',
 155:'stdout 重路由说明不能解释所有 resume.go 旧 Debug 的删除，需逐条对应。',
 165:'行内评审原版本不同于最终合并提交；用原评审 hunk、完整消息及最终目标 diff 作人工对应，不谎称 SHA 相同。',
 171:'原始 hook key 的 Debug 安全说明与 task checkpoint 目标日志不是同一处。',
 173:'PR 提到 phase transition 终端泄漏，而目标是 eager condense 警告，不可仅凭日志关键词对应。',
 188:'日志文本未变仍可能因 screen_gone 早退条件改变输出；这种目标不可机械标 unknown。',
 194:'分别检查前缀、ALS 字段与完成消息，实际替换不能因上游 deleted 被描述成取消输出。',
 198:'Sentry 迁移是整体背景；journal 移除、steps 字段移除及保留的 error 各自留存，不强行赋予隐私目的。',
 210:'PR main.cpp 日志格式改善与目标 Python wrapper 不一致。',
 224:'log every 10 batches 的说明需对应实际目标；所附事件多数为保留上下文或缺少目标 hunk。',
 228:'shared data prompt 可支持预热计时样例，另外两个缺少目标 diff 的事件不能直接继承该推断。',
 237:'import hoist 的总体目的不足以解释缺少目标 hunk 的日志事件。',
 249:'提交明确指向 Gitea PR #22；不把同号 GitHub issue 当作该 PR。',
 254:'仅声称 logging bug fix，具体缺陷与性能/噪声/安全目的均未交代。',
 270:'issue 所谈 orphan pruning 与大部分不变 print 不是同一日志变动，保留为背景。',
 293:'Big Beautiful Update 标题过宽；精确提交到 PR 的补查遭遇认证过期。',
 310:'Black 格式化背景不能自动说明语句本身不变的事件有日志特定目的。',
 316:'created GitHub issue 消息仍是 diff 上下文，不能继承 HMAC 诊断目的。',
 329:'同 session 的 gears 计划不足以解释 warning→debug；仅采用此修改提交点名的日志级别规范。',
 335:'同提交禁用 log_stats 的明确目的不直接说明 run_loop wrapper 本身（不变）的独立目的。',
 345:'与 fork 中事件分开保留；不得用非 2xx 代理错误日志说明解释成功 reachability 消息。',
}
