"""Run configuration. One object, passed explicitly; no globals."""
from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path


@dataclass(frozen=True)
class Config:
    out: Path = Path("out/aidev")                  # results root
    repos_dir: Path = Path("data/repos")           # clones (--no-checkout) live here
    source_dir: Path = Path("data/aidev")          # AIDev parquet tables

    # seeds: a commit is agent_commit only when its author is a bot login of the PR's own agent
    skip_merge_commits: bool = True                # "Merge ..." commits bring the base branch into the PR
    agent_bot_logins: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Copilot", ("Copilot",)),
        ("Devin", ("devin-ai-integration[bot]",)),
        ("Cursor", ("cursoragent",)),
        ("Google_Jules", ("google-labs-jules[bot]",)),
        ("Claude_Code", ("claude[bot]", "Claude Bot", "Claude", "claude")),
        ("OpenAI_Codex", ()),                      # Codex commits under the user's own account
    )

    # exclusion (never analysed): path components, file name suffixes, header markers, size
    exclude_dirs: tuple[str, ...] = ("site-packages", "dist-packages", "node_modules", "vendor", "_vendor",
                                     "third_party", "third-party", ".venv", "venv", ".tox", "build", "dist",
                                     "__pycache__", ".eggs")
    exclude_suffixes: tuple[str, ...] = ("_pb2.py", "_pb2_grpc.py")
    generated_markers: tuple[str, ...] = ("generated by", "do not edit", "@generated")
    max_file_bytes: int = 1_000_000
    suffixes: tuple[str, ...] = (".py",)

    # repo layer
    clone_timeout_s: int = 1800
    git_timeout_s: int = 600
    partial_clone: bool = True                     # --filter=blob:none: file contents fetched on demand
    fetch_pr_refs: bool = True                     # one `git fetch` of refs/pull/N/head per repository
    anchor_window_days: int = 30                   # patch-id / text fallback: mainline commits after merged_at

    # detection
    include_print: bool = True

    # tracking
    window_days: int = 90
    pair_threshold: float = 0.5                    # min similarity to pair statements inside one diff region
    move_threshold: float = 0.8                    # min similarity to pair outside a region / across files

    # parallelism
    workers: int = 4

    def with_(self, **kw) -> "Config":
        return replace(self, **kw)

    def bots(self) -> dict[str, frozenset[str]]:
        return {agent: frozenset(logins) for agent, logins in self.agent_bot_logins}
